name: Add new expansion url
description: Request addition of a new expansion url
title: "[Addition]: "
labels: ["addition"]
body:
  - type: markdown
    attributes:
      value: |
        Use this form to request adding a new expansion to the catalog. Please be aware that
        the expansion may be removed from the catalog if the download URL renders unavailable
        or it causes problems to Oolite or other expansions.

  - type: input
    id: download_url
    attributes:
      label: Download URL
      description: Public URL where the expansion can be downloaded from.
      placeholder: https://server/path_to_oxz
    validations: 
      required: true

  - type: input
    id: forum_thread
    attributes:
      label: Forum Thread
      description: The URL to the thread discussing the new expansion on https://bb.oolite.space. That thread needs to tell everyone the name of the oxp, what to expect, where they can download, and that you’re looking for testers. That thread will then become the main place to discuss your expansion going forward.
      placeholder: https://bb.oolite.space/viewtopic.php?t=
    validations: 
      required: true

  - type: input
    id: wiki_page
    attributes:
      label: Wiki Page
      description: The documentation page for your expansion. It should cover what users need to know and be updated according to the discussions in the forum thread. With that it prevents users from reading the full history just to be up to date.
      placeholder: https://wiki.alioth.net/index.php/...
    validations: 
      required: true        
