name: Build
on:
  schedule:
    - cron: '0 1 1 * *'
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download OoliteAddonScanner
      id: download
      uses: robinraju/release-downloader@v1.8
      with: 
        repository: "HiranChaudhuri/OoliteAddonScanner"
    
        # A flag to set the download target as latest release
        # The default value is 'false'
        latest: false
    
        # The github tag. e.g: v1.0.1
        # Download assets from a specific tag/version
        tag: "v1.0.54"
    
        # The release id to download files from 
        releaseId: ""
    
        # The name of the file to download.
        # Use this field only to specify filenames other than tarball or zipball, if any.
        # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
        fileName: "*.tar.gz"
    
        # Download the attached tarball (*.tar.gz)
        tarBall: false
    
        # Download the attached zipball (*.zip)
        zipBall: false
    
        # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
        # It will create the target directory automatically if not present
        # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
        out-file-path: ""

        # A flag to set if the downloaded assets are archives and should be extracted
        # Checks all downloaded files if they end with zip, tar or tar.gz and extracts them, if true.
        # Prints a warning if enabled but file is not an archive - but does not fail.
        extract: true

    - name: Restore expansions cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          expansion-cache
        key: ${{ runner.os }}-expansion_cache

    - name: check
      run: |
        set -x
        echo "Tag: ${{steps.download.outputs.tag_name}}"
        pwd
        printenv | sort
        find

    - name: "Run Generator/Scanner"
      run: |
        set -x
        OAS_VERSION="${{steps.download.outputs.tag_name}}"
        OAS_VERSION="${OAS_VERSION:1}"
        java -cp "./OoliteAddonScanner-${OAS_VERSION}/OoliteAddonScanner-${OAS_VERSION}.jar" com.chaudhuri.cataloggenerator.Main -in expansionUrls.txt  -out output/catalog/index -cache expansion-cache -format plist,json
        mv output/catalog/index.plist output/catalog/index.html
        mv output/catalog/index.json output/catalog/oxp.json

    - name: Check manifest
      run: |
        set -x
        find

    # See https://github.com/marketplace/actions/push-a-file-to-another-repository
    # but better to be replaced with https://github.com/marketplace/actions/push-dir
    - name: publish plist index
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.oolite_web_expansions_catalog_manager }}
      with:
        source_file: 'output/catalog/index.html'
        destination_repo: 'OoliteProject/oolite-web'
        destination_branch: only-media
        destination_folder: 'api/1.0/overview'
        user_email: 'builder@ooliteproject.org'
        user_name: 'builder'
        commit_message: '${{github.repository}} Job ${{github.job}} Run ${{github.run_number}}'

    - name: publish json index
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.oolite_web_expansions_catalog_manager }}
      with:
        source_file: 'output/catalog/oxp.json'
        destination_repo: 'OoliteProject/oolite-web'
        destination_branch: only-media
        destination_folder: 'data'
        user_email: 'builder@ooliteproject.org'
        user_name: 'builder'
        commit_message: '${{github.repository}} Job ${{github.job}} Run ${{github.run_number}}'

    - name: Save Expansions Cache
      id: cache-save
      uses: actions/cache/save@v3
      with:
        path: |
          expansion-cache
        key: ${{ runner.os }}-expansion_cache

